spring:
  datasource:
    url: jdbc:postgresql://database-1.c1pxamuubhjd.eu-central-1.rds.amazonaws.com/products
    username: postgres
    password: XJOFc2pfNhnVZpL3JWMr
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_mFJCXWt35
          jwk-set-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_mFJCXWt35/.well-known/jwks.json
springdoc:
  api-docs:
    path: /api-docs